config/routes.rb
Rails.application.routes.draw do

  resources :general_ledger_mappings
  resources :funding_sources, :path => :funding_programs do
    collection do
      get 'details'
      get 'find_fiscal_year_range'
    end
    resources :comments
    resources :documents
  end

  resources :grants do
    resources :grant_apportionments
    resources :grant_amendments

    member do
      get 'summary_info'
      get 'fire_workflow_event'
    end
  end



  resources :general_ledger_accounts do
    collection do
      get 'get_accounts'
      get 'check_grant_budget'
      get 'toggle_archive'
    end
  end

  resources :inventory, :only => [], :controller => 'assets' do
    collection do
      get 'get_general_ledger_account'
    end

    member do
      get 'get_book_value_on_date'
      get 'get_depreciation_months_left'
      get 'edit_depreciation'
      post 'update_depreciation'
    end

    resources :expenditures
  end

  resources :expenditures, :only => [] do
    resources :comments
    resources :documents
  end
end

app/models/general_ledger_account.rb
# --------------------------------
# # NOT USED see TTPLAT-1832 or https://wiki.camsys.com/pages/viewpage.action?pageId=51183790
# --------------------------------


#------------------------------------------------------------------------------
#
# GeneralLedgerAccount
#
# Represents a general ledger account that exists in an external accounting
# system. This model is used to associate assets with accounting system accounts
# in an external business system and is not designed to replicate a general ledger
#
#------------------------------------------------------------------------------
class GeneralLedgerAccount < ActiveRecord::Base

  # Include the object key mixin
  include TransamObjectKey

  #------------------------------------------------------------------------------
  # Callbacks
  #------------------------------------------------------------------------------
  after_initialize  :set_defaults

  # Clean up any HABTM associations before the asset is destroyed
  #before_destroy { grants.clear }


  #------------------------------------------------------------------------------
  # Associations
  #------------------------------------------------------------------------------

  # Every ledger account belongs to an chart of accounts
  belongs_to :chart_of_account

  # Every GLA has an account type
  belongs_to :general_ledger_account_type
  belongs_to :general_ledger_account_subtype

  has_many :general_ledger_account_entries, :dependent => :destroy

  has_many :grant_budgets, :dependent => :destroy, :inverse_of => :general_ledger_account

  #------------------------------------------------------------------------------
  # Validations
  #------------------------------------------------------------------------------

  validates :chart_of_account,              :presence => true
  validates :general_ledger_account_type,   :presence => true
  validates :general_ledger_account_subtype,   :presence => true
  validates :name,                          :presence => true
  validates :account_number,                :presence => true

  # List of allowable form param hash keys
  FORM_PARAMS = [
    :chart_of_account_id,
    :general_ledger_account_type_id,
    :general_ledger_account_subtype_id,
    :name,
    :account_number,
    :grant_id,
    :active,
  ]

  #------------------------------------------------------------------------------
  #
  # Scopes
  #
  #------------------------------------------------------------------------------

  default_scope { order(:account_number) }
  scope :active, -> { where(:active => true) }

  scope :asset_accounts, -> { where(:general_ledger_account_type => GeneralLedgerAccountType.find_by(name: 'Asset Account')) }
  scope :liability_accounts, -> { where(:general_ledger_account_type => GeneralLedgerAccountType.find_by(name: 'Liability Account')) }
  scope :equity_accounts, -> { where(:general_ledger_account_type => GeneralLedgerAccountType.find_by(name: 'Equity Account')) }
  scope :revenue_accounts, -> { where(:general_ledger_account_type => GeneralLedgerAccountType.find_by(name: 'Revenue Account')) }
  scope :expense_accounts, -> { where(:general_ledger_account_type => GeneralLedgerAccountType.find_by(name: 'Expense Account')) }

  scope :fixed_asset_accounts, -> { where(:general_ledger_account_subtype => GeneralLedgerAccountSubtype.find_by(name: 'Fixed Asset Account')) }
  scope :grant_funding_accounts, -> { where(:general_ledger_account_subtype => GeneralLedgerAccountSubtype.find_by(name: 'Grant Funding Account')) }
  scope :accumulated_depreciation_accounts, -> { where(:general_ledger_account_subtype => GeneralLedgerAccountSubtype.find_by(name: 'Accumulated Depreciation Account')) }
  scope :depreciation_expense_accounts, -> { where(:general_ledger_account_subtype => GeneralLedgerAccountSubtype.find_by(name: 'Depreciation Expense Account')) }
  scope :disposal_accounts, -> { where(:general_ledger_account_subtype => GeneralLedgerAccountSubtype.find_by(name: 'Disposal Account')) }

  #------------------------------------------------------------------------------
  #
  # Class Methods
  #
  #------------------------------------------------------------------------------

  def self.allowable_params
    FORM_PARAMS
  end

  #------------------------------------------------------------------------------
  #
  # Instance Methods
  #
  #------------------------------------------------------------------------------

  def fixed_asset_account?
    general_ledger_account_subtype.name == 'Fixed Asset Account'
  end

  def to_s
    account_number
  end

  def coded_name
    "#{account_number}-#{name}"
  end

  def subtotal
    general_ledger_account_entries.sum(:amount)
  end

  def asset_subtypes
    AssetSubtype.where(id: GeneralLedgerMapping.where('asset_account_id = ? OR depr_expense_account_id = ? OR accumulated_depr_account_id = ? OR gain_loss_account_id = ?', self, self, self, self).pluck(:asset_subtype_id))
  end

  #------------------------------------------------------------------------------
  #
  # Protected Methods
  #
  #------------------------------------------------------------------------------
  protected

    # Set resonable defaults for general ledger accounts
    def set_defaults
      self.general_ledger_account_type_id ||= self.general_ledger_account_subtype.try(:general_ledger_account_type_id)
      self.active = self.active.nil? ? true : self.active
    end

end

app/models/general_ledger_account_type.rb
# --------------------------------
# # NOT USED see TTPLAT-1832 or https://wiki.camsys.com/pages/viewpage.action?pageId=51183790
# --------------------------------


class GeneralLedgerAccountType < ActiveRecord::Base

  # Active scope -- always use this scope in forms
  scope :active, -> { where(active: true) }

  def to_s
    name
  end

end

app/controllers/general_ledger_accounts_controller.rb
# --------------------------------
# # NOT USED see TTPLAT-1832 or https://wiki.camsys.com/pages/viewpage.action?pageId=51183790
# --------------------------------


class GeneralLedgerAccountsController < OrganizationAwareController
  include FiscalYearHelper

  add_breadcrumb "Home", :root_path

  # Set the @chart_of_accounts and @ledger_account variable
  before_action :get_ledger_account, :only => [:show, :edit, :update, :destroy]

  # Protect the controller
  authorize_resource

  # Session Variables
  INDEX_KEY_LIST_VAR        = "general_ledger_accounts_list_cache_var"

  def index

    if params[:organization_id].present?
      @organization_id = params[:organization_id].to_i
    end
    if @organization_id.nil? || @organization_list.index(@organization_id).nil?
      @organization_id = @organization_list.first
    end

    @chart_of_accounts = Organization.find_by(id: @organization_id).chart_of_accounts

    if @organization_list.count > 1
      @total_rows = @organization_list.count
      org_idx = @organization_list.index(@organization_id)
      @row_number = org_idx+1
      @prev_record_key = Organization.find_by(id: @organization_list[org_idx-1]).chart_of_accounts.object_key if org_idx > 0
      @next_record_key = Organization.find_by(id: @organization_list[org_idx+1]).chart_of_accounts.object_key if org_idx < @organization_list.count - 1

      @prev_record_path = @prev_record_key.nil? ? "#" : capital_plan_path(@prev_record_key)
      @next_record_path = @next_record_key.nil? ? "#" : capital_plan_path(@next_record_key)
    end

     # Start to set up the query
    conditions  = []
    values      = []

    @account_type_id = params[:type]
    unless @account_type_id.blank?
      @account_type_id = @account_type_id.to_i
      conditions << 'general_ledger_account_type_id = ?'
      values << @account_type_id

      account_type = GeneralLedgerAccountType.find(@account_type_id)
      add_breadcrumb account_type, general_ledger_accounts_path(:type => account_type)

    end

    @account_subtype_id = params[:subtype]
    unless @account_subtype_id.blank?
      @account_subtype_id = @account_subtype_id.to_i
      conditions << 'general_ledger_account_subtype_id = ?'
      values << @account_subtype_id

      account_subtype = GeneralLedgerAccountSubtype.find(@account_subtype_id)
      add_breadcrumb account_subtype, general_ledger_accounts_path(:subtype => account_subtype)

    end

    @ledger_accounts = @chart_of_accounts.general_ledger_accounts.where(conditions.join(' AND '), *values).order(:name)

    add_breadcrumb @chart_of_accounts, general_ledger_accounts_path(organization_id: @chart_of_accounts.organization_id)

    # cache the set of accounts ids in case we need them later
    cache_list(@ledger_accounts, INDEX_KEY_LIST_VAR)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @ledger_accounts }
    end
  end

  def toggle_archive
    coa = ChartOfAccount.find_by(id: params[:chart_of_account_id])

    if coa.present?
      if ArchivedFiscalYear.archive(coa.organization_id, params[:fy_year], true)
        notify_user(:notice, "The #{get_fy_label} was successfully archived/unarchived.")
      else
        notify_user(:alert, "Cannot archive/unarchive #{get_fy_label}.")
      end

      redirect_to general_ledger_accounts_path(organization_id: coa.organization_id)
    else
      redirect_to '/404'
    end
  end

  def show

    add_breadcrumb @chart_of_accounts, general_ledger_accounts_path(organization_id: @chart_of_accounts.organization_id)
    add_breadcrumb @ledger_account

    # get the @prev_record_path and @next_record_path view vars
    get_next_and_prev_object_keys(@ledger_account, INDEX_KEY_LIST_VAR)
    @prev_record_path = @prev_record_key.nil? ? "#" : general_ledger_account_path(@prev_record_key)
    @next_record_path = @next_record_key.nil? ? "#" : general_ledger_account_path(@next_record_key)

    respond_to do |format|
      format.html # show.html.erb
      format.js
      format.json { render :json => @ledger_account }
    end
  end

  # GET /general_ledger_accounts/new
  def new

    if params[:chart_of_account_id].nil?
      notify_user(:warning, 'Cannot create GLA without a chart of account.')
      redirect_to general_ledger_accounts_path
    else
      @chart_of_accounts = ChartOfAccount.find_by(id: params[:chart_of_account_id])
      add_breadcrumb @chart_of_accounts, general_ledger_accounts_path(organization_id: @chart_of_accounts.organization_id)
      add_breadcrumb "New", new_general_ledger_account_path
      @ledger_account = GeneralLedgerAccount.new
    end

  end

  # GET /general_ledger_accounts/1/edit
  def edit
    add_breadcrumb @chart_of_accounts, general_ledger_accounts_path(organization_id: @chart_of_accounts.organization_id)
    add_breadcrumb @ledger_account
    add_breadcrumb "Update"

  end

  def get_accounts
    case params[:subtype]
      when 'fixed_asset'
        result = GeneralLedgerAccount.fixed_asset_accounts.where(chart_of_account_id: params[:chart_of_account_id])
      when 'depreciation_expense'
        result = GeneralLedgerAccount.depreciation_expense_accounts.where(chart_of_account_id: params[:chart_of_account_id])
      when 'accumulated_depreciation'
        result = GeneralLedgerAccount.accumulated_depreciation_accounts.where(chart_of_account_id: params[:chart_of_account_id])
      when 'disposal'
        result = GeneralLedgerAccount.disposal_accounts.where(chart_of_account_id: params[:chart_of_account_id])
      else
        result = GeneralLedgerAccount.where(chart_of_account_id: params[:chart_of_account_id])
    end

    respond_to do |format|
      format.json { render json: result.map{|x| [x.id, x.coded_name]}.to_json }
    end
  end

  def check_grant_budget
    @grant = Grant.find_by(id: params[:grant_id])
    available = @grant.amount - @grant.grant_budgets.sum(:amount)

    respond_to do |format|
      format.json { render :json => available.to_json }
    end
  end

  # POST /general_ledger_accounts
  # POST /general_ledger_accounts.json
  def create

    @ledger_account = GeneralLedgerAccount.new(form_params)

    respond_to do |format|
      if @ledger_account.save
        notify_user(:notice, "The general ledger account was successfully saved.")

        format.html { redirect_to general_ledger_account_url(@ledger_account) }
        format.json { render action: 'show', status: :created, location: @ledger_account }
      else
        format.html { render action: 'new' }
        format.json { render json: @ledger_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /general_ledger_accounts/1
  # PATCH/PUT /general_ledger_accounts/1.json
  def update

    respond_to do |format|
      if @ledger_account.update(form_params)
        notify_user(:notice, "The general ledger account was successfully updated.")
        format.html { redirect_to general_ledger_account_url(@ledger_account) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ledger_account.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @ledger_account.general_ledger_account_entries.count == 0
      @ledger_account.destroy
      redirect_to general_ledger_accounts_url, notice: 'General ledger account was successfully destroyed.'
    else
      redirect_to @ledger_account, notice: 'General ledger account cannot be destroyed as there are entries in its ledger.'
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def form_params
    params.require(:general_ledger_account).permit(GeneralLedgerAccount.allowable_params)
  end

  def get_ledger_account
    chart_of_account_ids = ChartOfAccount.where(organization_id: @organization_list).ids
    @ledger_account = GeneralLedgerAccount.find_by(object_key: params[:id], chart_of_account_id: chart_of_account_ids)

    # if not found or the object does not belong to the users
    # send them back to index.html.erb
    if @ledger_account.nil?
      chart_of_account_ids = ChartOfAccount.where(organization_id: current_user.user_organization_filters.system_filters.first.get_organizations.map{|x| x.id}).ids
      if GeneralLedgerAccount.find_by(object_key: params[:id], chart_of_account_id: chart_of_account_ids).nil?
        redirect_to '/404'
      else
        notify_user(:warning, 'This record is outside your filter. Change your filter if you want to access it.')
        redirect_to general_ledger_accounts_path
      end
      return
    else
      @chart_of_accounts = @ledger_account.chart_of_account
    end

  end

end

app/views/general_ledger_accounts/_actions.html.haml
- if @ledger_account.fixed_asset_account?
  .btn-group.pull-right.panel-action
    %button.btn.btn-primary.btn-sm.dropdown-toggle{:data => {:toggle => 'dropdown'}}
      %i.fa.fa-cog
      = " Actions"
      %span.caret
    %ul.dropdown-menu{:role => 'menu'}
      - if can? :update, @ledger_account
        %li
          = link_to edit_general_ledger_account_path(@ledger_account) do
            %i.fa.fa-edit.fa-fw
            = " Update this general ledger account"

app/views/general_ledger_accounts/_details.html.haml
%ul.nav.nav-tabs
  %li
    %a{:href => "#subtypes", :data =>{:toggle => 'tab'}}
      %span.badge.pull-right= @ledger_account.asset_subtypes.count
      = "Asset Subtypes"
  %li
    %a{:href => "#gla_entries", :data =>{:toggle => 'tab'}}
      %span.badge.pull-right= @ledger_account.general_ledger_account_entries.count
      = "GL Account Entries"

.tab-content
  .tab-pane.fade#subtypes
    .tab-content
      = format_field("Asset Subtypes", format_as_list(@ledger_account.asset_subtypes))
  .tab-pane.fade#gla_entries
    .tab-content
      = render :partial => 'gla_entries', :locals => {:gla_entries => @ledger_account.general_ledger_account_entries.from_fy(Organization.get_typed_organization(@ledger_account.chart_of_account.organization).first_archivable_fiscal_year)}

app/views/general_ledger_accounts/_form.html.haml
= simple_form_for(@ledger_account,
  :html => {:class => 'form-vertical gla_form'},
  :wrapper => :vertical_form,
  :wrapper_mappings => {:check_boxes => :vertical_radio_and_checkboxes,
  :radio_buttons => :vertical_radio_and_checkboxes,
  :file => :vertical_file_input,
  :boolean => :vertical_boolean}) do |f|

  = f.input :chart_of_account_id, :as => :hidden, :input_html => {:value => @chart_of_accounts.id}

  = f.association :general_ledger_account_type, :collection => @ledger_account.new_record? ? GeneralLedgerAccountType.active.where(name: 'Asset Account') : GeneralLedgerAccountType.active, :label => 'Account Type', :include_blank => false
  = f.association :general_ledger_account_subtype, :collection => @ledger_account.new_record? ? GeneralLedgerAccountSubtype.active.where(name: 'Fixed Asset Account') : GeneralLedgerAccountSubtype.active, :label => 'Account Subtype', :include_blank => false
  = f.input :name, :required => true
  = f.input :account_number, :required => true

  = f.button :submit, :class => "btn btn-primary"

:javascript
  
  $('.gla_form').validate({
    submitHandler: function(form) {
      form.submit();
    }
  });

app/views/general_ledger_accounts/_gl_accounts_table.html.haml
- if gl_accounts.empty?
  %p There are no grants associated with this account.
-else
  %table.table.table-hover#datatable
    %thead
      %tr
        %th.left Name
        %th.right Account Number
        %th.right Account Type

    %tbody
      - gl_accounts.each do |a|
        %tr.popup-details{:data => {:action_path => general_ledger_account_path(a)}}
          %td.left= a.name
          %td.right= a.account_number
          %td.right= a.general_ledger_account_type.name

  = render 'shared/datatable_javascript'

app/views/general_ledger_accounts/_gla_budgets.html.haml
- if gla_budgets.empty?
  %p There are no associated GLA budgets.
-else
  %table.table.table-hover#gla_datatable
    %thead
      %tr
        %th.left Grant
        %th.left GLA
        %th.right Budget
        %th.right Balance

    %tbody
      - gla_budgets.each do |gla_budget|
        - grant_gla = GeneralLedgerAccount.where('account_number = ? AND name LIKE ?', "#{@ledger_account.account_number}-#{gla_budget.grant}","%Funding").where(grant: gla_budget.grant).first
        %tr.popup-details
          %td.left= link_to gla_budget.grant, grant_path(gla_budget.grant)
          %td.left= link_to grant_gla, general_ledger_account_path(grant_gla)
          %td.right= format_as_currency(gla_budget.amount)
          %td.right= format_as_currency(grant_gla.subtotal)

:javascript
  $('.popup-details').popover({
    trigger: 'hover',
    container: 'body',
    placement: 'left',
    animation: 'true',
    html: 'true'
  });

app/views/general_ledger_accounts/_gla_entries.html.haml
- if gla_entries.empty?
  %p There are no entries in this GL account.
-else
  %table.table.table-hover#gla_datatable{:data => {:toggle => 'table',
      :pagination => 'true',
      :show_pagination_switch => 'false',
      :page_list => "5, 10, 20, 50, 100, 200, 10000]",
      :page_size => current_user.num_table_rows,
      :search => 'false',
      :export_types => "['csv', 'txt', 'excel']",
      :show_export => 'true',
      :show_toggle => 'false',
      :cookie => 'true',
      :cookie_id_table => "gla_entries_id",
      :cookie_expire => "1y"}}
    %thead
      %tr
        %th.left Date
        %th.left Description
        %th.right Change
        %th.right Balance


    %tbody
      - balance = 0
      - gla_entries.each_with_index do |gla_entry,idx|
        %tr.popup-details
          %td.left= format_as_date(gla_entry.event_date)
          %td.left= gla_entry.description.html_safe
          %td.right= format_as_currency(gla_entry.amount)
          - balance += gla_entry.amount
          %td.right= format_as_currency(balance)

:javascript
  $('.popup-details').popover({
    trigger: 'hover',
    container: 'body',
    placement: 'left',
    animation: 'true',
    html: 'true'
  });

  $("#gla_datatable").on('all.bs.table', function(evt, name, args) {
    $('.fixed-table-container').css('min-height', '300px')
    transam.make_same_height('.header-part');
  });

  $(window).load(function() {
    transam.make_same_height('.header-part');
  });

  $(window).resize(function() {
    $("#gla_datatable").bootstrapTable('resetView');
  });

app/views/general_ledger_accounts/_index_actions.html.haml
- if can? :create, GeneralLedgerAccount
  -#= link_to new_general_ledger_account_path(chart_of_account_id: @chart_of_accounts.id), :class => 'btn btn-default' do
  -#  %i.fa.fa-plus.fa-fw
  -#  = " Add General Ledger Account";
  = link_to general_ledger_mappings_path(chart_of_account_id: @chart_of_accounts.id), :class => 'btn btn-default' do
    %i.fa.fa-map-signs.fa-fw
    = " GL Mappings"
- if can? :manage, GeneralLedgerAccount
  .btn-group{:role => 'group'}
    %button.btn.btn-info.move-assets-button{:type => 'button'}
      %i.fa.fa-tasks
      %span#button-text Archive
    %button.btn.btn-info.move-assets-button.dropdown-toggle{:type => 'button', :data => {:toggle => 'dropdown'}, :aria => {:haspopup => 'true', :expanded => 'false'}}
      %span.caret
      %span.sr-only Toggle Dropdown
    %ul.dropdown-menu
      - archivable_fy = Organization.get_typed_organization(@chart_of_accounts.organization).first_archivable_fiscal_year
      - get_fiscal_years(start_of_fiscal_year(archivable_fy), current_fiscal_year_year - archivable_fy).each do |fy|
        %li
          = link_to fy[0], toggle_archive_general_ledger_accounts_path(chart_of_account_id: @chart_of_accounts.id, fy_year: fy[1])

app/views/general_ledger_accounts/_index_table.html.haml
:ruby
  table_dom_id = SecureRandom.hex
  show_actions ||= 0

- if show_actions == 1
  #table_actions.btn-group
    = render :partial => "general_ledger_accounts/index_actions"

%table.table.table-hover{:id => table_dom_id, :data => {:toggle => 'table',
  :card_view => "false",
  :pagination => 'true',
  :page_list => "5, 10, 20, 50, 100, 200, 10000]",
  :page_size => current_user.num_table_rows,
  :show_pagination_switch => 'false',
  :search => 'false',
  :show_columns => 'true',
  :show_export => 'true',
  :show_toggle => 'true',
  :resizable => 'true',
  :search => 'false',
  :cookie => 'true',
  :cookie_id_table => "general_ledger_accounts_id",
  :cookie_expire => "1y"}}
  %thead
    %tr
      %th.left{:data => {:sortable => 'true', :order => 'desc'}} Account Number
      %th.left{:data => {:sortable => 'true', :order => 'desc'}} Name
      %th.left{:data => {:sortable => 'true'}} Balance


  %tbody
    - gl_accounts.each do |a|
      %tr.popup-details{:id => a.object_key, :class => 'action-path', :data => {:action_path => general_ledger_account_path(a)}}
        %td.right= a.account_number
        %td.left= a.name
        %td.right= format_as_currency(a.subtotal)


= render :partial => 'shared/table_scripts', :locals => {:table_id => table_dom_id, :path_pattern => general_ledger_account_path("xxx")}

app/views/general_ledger_accounts/_scripts.html.haml
:javascript

  var user_tab_key = 'general_ledger_account_tab_key';

  $(document).ready(function() {

    transam.make_same_height('.header-part');

    // Manage the tabs
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e) {
      // save the latest tab
      var this_tab = $(this).attr('href');
      transam.set_ui_key_value(user_tab_key, this_tab);
      transam.make_same_height('.header-part');
    });
  });
  $(function() {
    var last_tab = transam.get_ui_key_value(user_tab_key);
    if (last_tab) {
      $('a[href="'+last_tab+'"]').tab('show');
    } else {
      // Default to the first tab if no tab is stored
      $('a[data-toggle="tab"]:first').tab('show');
    }
  });

app/views/general_ledger_accounts/_summary.html.haml
= format_field("Name", ledger_account.name )
= format_field("Account Number", ledger_account.account_number)
= format_field("Account Type", ledger_account.general_ledger_account_type)
= format_field("Account Subtype", ledger_account.general_ledger_account_subtype )
%hr
= format_field("Balance", format_as_currency(ledger_account.subtotal))

app/views/general_ledger_accounts/edit.html.haml
.row
  .col-md-6.col-md-offset-3
    %fieldset
      %legend Update General Ledger Account
      = render(:partial => 'shared/form_errors', :locals => {:obj => @ledger_account}) unless @ledger_account.errors.empty?

      = render 'form'

= render 'scripts'

app/views/general_ledger_accounts/index.html.haml
.col-sm-12.col-md-10.col-md-offset-1
  .page-header
    %h2= @chart_of_accounts

  .row
    .col-sm-12
      = render :partial => 'index_table', :locals => {:gl_accounts => @ledger_accounts, :show_actions => 1}

app/views/general_ledger_accounts/new.html.haml
.row
  .col-md-6.col-md-offset-3
    %fieldset
      %legend New General Ledger Account
      = render(:partial => 'shared/form_errors', :locals => {:obj => @ledger_account}) unless @ledger_account.errors.empty?

      = render 'form'

= render 'scripts'

app/views/general_ledger_accounts/show.html.haml
.row
  .col-md-3
    .panel.panel-default.header-part
      .panel-heading
        .row
          .col-md-6
            %h3.panel-title
              %i.fa.fa-list
              General Ledger Account
          .col-md-6
            = render 'actions'
      .panel-body
        = render :partial => 'summary', :locals => {:ledger_account => @ledger_account}

  .col-md-9
    .panel.panel-default.header-part
      .panel-heading
        .row
          .col-md-12
            %h3.panel-title
              %i.fa.fa-folder-open
              Details

      .panel-body
        = render 'details'

= render 'scripts'