config/routes.rb
Rails.application.routes.draw do

  resources :general_ledger_mappings
  resources :funding_sources, :path => :funding_programs do
    collection do
      get 'details'
      get 'find_fiscal_year_range'
    end
    resources :comments
    resources :documents
  end

  resources :grants do
    resources :grant_apportionments
    resources :grant_amendments

    member do
      get 'summary_info'
      get 'fire_workflow_event'
    end
  end



  resources :general_ledger_accounts do
    collection do
      get 'get_accounts'
      get 'check_grant_budget'
      get 'toggle_archive'
    end
  end

  resources :inventory, :only => [], :controller => 'assets' do
    collection do
      get 'get_general_ledger_account'
    end

    member do
      get 'get_book_value_on_date'
      get 'get_depreciation_months_left'
      get 'edit_depreciation'
      post 'update_depreciation'
    end

    resources :expenditures
  end

  resources :expenditures, :only => [] do
    resources :comments
    resources :documents
  end
end

app/views/shared/_accounting_nav.html.haml
%li.nav-item{:class => get_nav_link_class(['accounting'])}
  = link_to "#", :class => "dropdown-toggle", :data => {"toggle" => "dropdown"} do
    %i.fa.fa-usd.fa-2x
    %br
    Accounting
    %b.caret
  %ul.dropdown-menu.multi-level{:role => 'menu'}      
    %li.text-left
      = link_to general_ledger_accounts_path do
        %i.fa.fa-usd.fa-fw
        Chart of Accounts

app/views/shared/_accounting_quick_links.html.haml
- if can? :create, Expenditure
  = render :partial => 'quick_link', :locals => {:action_title => 'CapEx', :action_path => new_expenditure_path, :action_icon => 'fa fa-plus'}

app/views/shared/_financial_nav.html.haml
%li{:class => get_nav_link_class(['accounting'])}
  = link_to "#", :class => "dropdown-toggle", :style => 'padding-top:19px;', :data => {"toggle" => "dropdown"} do
    %i.fa.fa-usd.fa-lg
    Accounting
    %b.caret
  %ul.dropdown-menu.multi-level{:role => 'menu'}

    - count = 0
    - if ChartOfAccount.where(organization_id: @organization_list).count > 0
      - count += 1
      - if @organization_list.count == 1
        %li.text-left
          = link_to general_ledger_accounts_path do
            %i.fa.fa-book.fa-fw
            Chart of Accounts
      - else
        %li.text-left.dropdown-submenu
          = link_to '#' do
            %i.fa.fa-book.fa-fw
            Chart of Accounts

          %ul.dropdown-menu
            - Organization.where(id: @organization_list).each do |org|
              %li.text-left
                = link_to general_ledger_accounts_path(:organization_id => org.id) do
                  %i.fa.fa-fw.fa-book
                  = org.short_name

      - if SearchType.find_by(class_name: 'GeneralLedgerAccountSearcher')
        - if count > 0
          %li.divider
        - count += 1
        %li.text-left
          = link_to reset_searches_path(:search_type => SearchType.find_by(class_name: 'GeneralLedgerAccountSearcher').id) do
            %i.fa.fa-search.fa-fw
            GL Query

    -#%li.divider
    -#%li.text-left
    -#  = link_to grants_path do
    -#    %i.fa.fa-fw.fa-legal
    -#    = ' Grants'
    -#
    -#%li.divider
    -#%li.text-left
    -#  = link_to vendors_path do
    -#    %i.fa.fa-fw.fa-tag
    -#    = ' Vendors'

    - if count > 0
      %li.divider
    %li.text-left
      = link_to funding_sources_path do
        %i.fa.fa-book.fa-fw
        Programs

      -# %ul.dropdown-menu
      -#   - FundingSourceType.all.each do |type|
      -#     - if FundingSource.where(funding_source_type_id: type.id).count > 0
      -#       %li.text-left.dropdown-submenu
      -#         = link_to '#' do
      -#           %i.fa.fa-fw.fa-book
      -#           = type
      -#         %ul.dropdown-menu
      -#           - FundingSource.where(funding_source_type_id: type.id).each do | program |
      -#             %li.text-left
      -#               = link_to funding_source_path(program) do
      -#                 %i.fa.fa-fw.fa-book
      -#                 = program
      -#   - if can? :create, FundingSource
      -#     - if FundingSource.all.count > 0
      -#       %li.divider
      -#     %li
      -#       = link_to new_funding_source_path do
      -#         %i.fa.fa-plus.fa-fw
      -#         = "Add Funding Program";

    - SystemConfig.transam_module_names.each do |mod|
      - view_component = "#{mod}_financial_nav"
      - if lookup_context.template_exists?(view_component, 'shared', true)
        - count += 1
        = render :partial => "shared/#{view_component}", :locals => {:count => count}

    - if (can? :read, Grant) && !(SystemConfig.transam_module_names.include? 'funding')
      %li.divider
      %li.text-left
        = link_to grants_path do
          %i.fa.fa-balance-scale.fa-fw
          Grants

app/views/shared/_main_nav.html.haml
%ul.nav.navbar-nav.collapse.navbar-collapse
  :javascript
    $('.navbar-fixed-top ul.navbar-collapse').addClass('hide-during-load');
  %li{:class => get_nav_link_class('dashboards') }
    = link_to dashboards_path, :style => 'padding-top:19px;' do
      %i.fa.fa-home.fa-lg
      Home

  = render 'shared/inventory_nav'
  = render 'shared/policy_nav'
  = render 'shared/financial_nav'

  -# render the engine main nav components if there are any
  - SystemConfig.transam_module_names.each do |mod|
    - view_component = "#{mod}_main_nav"
    - if lookup_context.template_exists?(view_component, 'shared', true)
      = render :partial => "shared/#{view_component}"

  -# render the application main nav components if there are any
  - view_component = "app_main_nav"
  - if lookup_context.template_exists?(view_component, 'shared', true)
    = render :partial => "shared/#{view_component}"

  = render 'shared/maintenance_nav'
  = render 'shared/reports_nav'
  = render 'shared/notifications_nav'
  = render 'shared/help_nav'