config/routes.rb
Rails.application.routes.draw do

  resources :general_ledger_mappings
  resources :funding_sources, :path => :funding_programs do
    collection do
      get 'details'
      get 'find_fiscal_year_range'
    end
    resources :comments
    resources :documents
  end

  resources :grants do
    resources :grant_apportionments
    resources :grant_amendments

    member do
      get 'summary_info'
      get 'fire_workflow_event'
    end
  end



  resources :general_ledger_accounts do
    collection do
      get 'get_accounts'
      get 'check_grant_budget'
      get 'toggle_archive'
    end
  end

  resources :inventory, :only => [], :controller => 'assets' do
    collection do
      get 'get_general_ledger_account'
    end

    member do
      get 'get_book_value_on_date'
      get 'get_depreciation_months_left'
      get 'edit_depreciation'
      post 'update_depreciation'
    end

    resources :expenditures
  end

  resources :expenditures, :only => [] do
    resources :comments
    resources :documents
  end
end

app/models/funding_source.rb
#------------------------------------------------------------------------------
#
# FundingSource
#
# Represents a funding source used to purchase assets. Each funding source can
# be associated with 0 or more grants
#
#------------------------------------------------------------------------------
class FundingSource < ActiveRecord::Base

  # Include the object key mixin
  include TransamObjectKey

  # Include the fiscal year mixin
  include FiscalYear

  #------------------------------------------------------------------------------
  # Callbacks
  #------------------------------------------------------------------------------
  after_initialize                  :set_defaults

  default_scope { where(funding_source_type: FundingSourceType.active) }

  #------------------------------------------------------------------------------
  # Associations
  #------------------------------------------------------------------------------

  # Has a single funding source type
  belongs_to  :funding_source_type

  # Each funding source was created and updated by a user
  belongs_to :creator, -> { unscope(where: :active) }, :class_name => "User", :foreign_key => :created_by_id
  belongs_to :updator, -> { unscope(where: :active) }, :class_name => "User", :foreign_key => :updated_by_id

  # Each funding program has zero or more documents. Documents are deleted when the program is deleted
  has_many    :documents,   :as => :documentable, :dependent => :destroy

  # Each funding program has zero or more comments. Documents are deleted when the program is deleted
  has_many    :comments,    :as => :commentable,  :dependent => :destroy

  # Has many grants
  has_many    :grants, :as => :sourceable, :dependent => :destroy

  has_many :grant_purchases, :as => :sourceable, :dependent => :destroy
  has_many :assets, through: :grant_purchases, source: Rails.application.config.asset_base_class_name.underscore

  # program eligibility - a program has many organizations
  has_and_belongs_to_many :organizations

  #------------------------------------------------------------------------------
  # Validations
  #------------------------------------------------------------------------------
  validates :name,                      :presence => true, :uniqueness => true
  validates :description,               :presence => true
  validates :funding_source_type,       :presence => true

  validates :life_in_years,             :allow_nil => true, :numericality => {:greater_than_or_equal_to => 1, :only_integer => true}
  validates :match_required,            :presence => true, :numericality => {:greater_than => 0.0, :less_than_or_equal_to => 100.0}
  validates :fy_start,                  :allow_nil => true, :numericality => {:only_integer => true}
  validates :fy_end,                    :allow_nil => true, :numericality => {:only_integer => true}
  validates :inflation_rate,            :allow_nil => true, :numericality => {:greater_than_or_equal_to => 0.0, :less_than_or_equal_to => 100.0}

  validate :validate_fy_start_less_than_or_equal_fy_end
  validate :validate_either_formula_or_discretionary

  #------------------------------------------------------------------------------
  # Scopes
  #------------------------------------------------------------------------------

  # List of hash parameters allowed by the controller
  FORM_PARAMS = [
    :object_key,
    :name,
    :full_name,
    :description,
    :details,
    :funding_source_type_id,
    :life_in_years,
    :match_required,
    :fy_start,
    :fy_end,
    :formula_fund,
    :discretionary_fund,
    :inflation_rate,
    {:organization_ids => []},
    :active
  ]

  #------------------------------------------------------------------------------
  #
  # Class Methods
  #
  #------------------------------------------------------------------------------

  def self.allowable_params
    FORM_PARAMS
  end

  def self.active
    where('(fy_start IS NULL OR fy_start <= ?) AND (fy_end IS NULL OR fy_end >= ?)', current_planning_year_year, current_planning_year_year)
  end

  def self.current_planning_year_year
    FundingSource.new.current_planning_year_year
  end

  def find_all_valid_fiscal_years
    unless self.fy_start.nil?
      program_start = start_of_fiscal_year(self.fy_start)
      program_years_to_end = self.fy_end - self.fy_start
    else
      program_start = nil
      program_years_to_end = nil
    end

    get_fiscal_years(program_start, program_years_to_end)
  end

  #------------------------------------------------------------------------------
  #
  # Instance Methods
  #
  #------------------------------------------------------------------------------

  def deleteable?
    true
  end

  # Generates a cash forecast for the funding source
  def cash_forecast(org_id = nil)

    if org_id
      line_items = funding_line_items.where('organization_id = ?', org_id)
    else
      line_items = funding_line_items
    end

    first_year = line_items.empty? ? current_fiscal_year_year : line_items.first.fy_year

    a = []
    cum_amount = 0
    cum_spent = 0
    cum_committed = 0

    (first_year..last_fiscal_year_year).each do |yr|
      year_amount = 0
      year_spent = 0
      year_committed = 0

      list = line_items.where('fy_year = ?', yr)
      list.each do |fli|
        year_amount += fli.amount
        year_spent += fli.spent
        year_committed += fli.committed
      end

      cum_amount += year_amount
      cum_spent += year_spent
      cum_committed += year_committed

      # Add this years summary to the cumulative amounts
      a << [fiscal_year(yr), cum_amount, cum_spent, cum_committed]
    end
    a

  end

  # Generates a cash flow for the funding source
  def cash_flow(org = nil)

    if org
      line_items = grants.where('organization_id = ?', org.id)
    else
      line_items = grants
    end

    first_year = line_items.empty? ? current_fiscal_year_year : line_items.first.fy_year

    a = []
    balance = 0

    (first_year..last_fiscal_year_year).each do |yr|
      year_amount = 0
      year_spent = 0
      year_committed = 0

      list = line_items.where('fy_year = ?', yr)
      list.each do |fli|
        year_amount += fli.amount
        year_spent += fli.spent
        year_committed += fli.committed
      end

      balance += year_amount - (year_spent + year_committed)

      # Add this years summary to the array
      a << [fiscal_year(yr), year_amount, year_spent, year_committed, balance]
    end
    a

  end

  def federal?
    (funding_source_type_id == FundingSourceType.find_by(name: 'Federal').id)
  end

  def to_s
    name
  end

  #------------------------------------------------------------------------------
  #
  # Protected Methods
  #
  #------------------------------------------------------------------------------
  protected

  # Set resonable defaults for a new capital project
  def set_defaults
    self.active = self.active.nil? ? true : self.active
  end

  def validate_fy_start_less_than_or_equal_fy_end
    valid = true
    if self.fy_start.present? && self.fy_end.present?
      valid = (fy_start <= fy_end)
    end

    valid
  end

  def validate_either_formula_or_discretionary
    self.formula_fund || self.discretionary_fund
  end
end

app/models/funding_source_type.rb
#------------------------------------------------------------------------------
#
# FundingSourceType
#
# Lookup Table for types of funding sources. Initially: state/federal/local.
#
#------------------------------------------------------------------------------
class FundingSourceType < ActiveRecord::Base

  # Has many funding sources
  has_many    :funding_sources

  # All types that are available

  default_scope { active }

  scope :active, -> { where(:active => true) }
  scope :funding_program, -> { where("name != 'Agency'") }
 
  def to_s
    name
  end

end

app/controllers/funding_sources_controller.rb
class FundingSourcesController < OrganizationAwareController

  # Include the fiscal year mixin
  include FiscalYear

  authorize_resource :except => :details
  protect_from_forgery except: :edit

  add_breadcrumb "Home", :root_path
  add_breadcrumb "Funding Programs", :funding_sources_path

  before_action :check_for_cancel,        :only => [:create, :update]
  before_action :set_funding_source,      :only => [:show, :edit, :update, :destroy]

  INDEX_KEY_LIST_VAR    = "funding_source_key_list_cache_var"

  # GET /funding_sources
  # GET /funding_sources.json
  def index

     # Start to set up the query
    conditions  = []
    values      = []

    @funding_source_type_id = params[:funding_source_type_id]
    unless @funding_source_type_id.blank?
      @funding_source_type_id = @funding_source_type_id.to_i
      conditions << 'funding_source_type_id = ?'
      values << @funding_source_type_id
    end

    if params[:show_active_only].nil?
      @show_active_only = '1'
    else
      @show_active_only = params[:show_active_only]
    end

    # allowing for add funding program flyout button
    @funding_source = FundingSource.new


    #puts conditions.inspect
    #puts values.inspect
    @funding_sources = @show_active_only == '1' ? FundingSource.active.includes(:funding_source_type).where(conditions.join(' AND '), *values).order(:name) : FundingSource.includes(:funding_source_type).where(conditions.join(' AND '), *values).order(:name)

    # cache the set of object keys in case we need them later
    cache_list(@funding_sources, INDEX_KEY_LIST_VAR)

    if @funding_source_type_id.blank?
      add_breadcrumb "All"
    else
      add_breadcrumb FundingSourceType.find(@funding_source_type_id)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @funding_sources }
    end

  end

  # returns details for an funding source as a JSON string
  def details

    if params[:funding_line_item_id]
      line_item = FundingLineItem.find(params[:funding_line_item_id])
      @funding_source = line_item.funding_source
    elsif params[:funding_source_id]
      @funding_source = FundingSource.find(params[:funding_source_id])
    end

    respond_to do |format|
      format.js
      format.json { render :json => @funding_source.to_json }
    end

  end

  # GET /funding_sources/1
  # GET /funding_sources/1.json
  def show

    add_breadcrumb @funding_source.name, funding_source_path(@funding_source)

    # Set the funding line items
    @grants = @funding_source.grants.where('organization_id = ?', @organization.id).order('fy_year')

    # get the @prev_record_path and @next_record_path view vars
    get_next_and_prev_object_keys(@funding_source, INDEX_KEY_LIST_VAR)
    @prev_record_path = @prev_record_key.nil? ? "#" : funding_source_path(@prev_record_key)
    @next_record_path = @next_record_key.nil? ? "#" : funding_source_path(@next_record_key)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @funding_source }
    end

  end

  # GET /funding_sources/new
  def new

    add_breadcrumb "New", new_funding_source_path

    @funding_source = FundingSource.new

  end

  # GET /funding_sources/1/edit
  def edit

    add_breadcrumb @funding_source.name, funding_source_path(@funding_source)
    add_breadcrumb "Update"

    respond_to do |format|
      format.html
      format.json { render :json => @funding_source }
      format.js
    end

  end

  # POST /funding_sources
  # POST /funding_sources.json
  def create

    @funding_source = FundingSource.new(form_params)
    @funding_source.creator = current_user
    @funding_source.updator = current_user

    respond_to do |format|
      if @funding_source.save
        notify_user(:notice, "The funding program was successfully saved.")
        format.html { redirect_to funding_source_url(@funding_source) }
        format.json { render action: 'show', status: :created, location: @funding_source }
      else
        format.html { render action: 'new' }
        format.json { render json: @funding_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funding_sources/1
  # PATCH/PUT /funding_sources/1.json
  def update

    @funding_source.updator = current_user

    respond_to do |format|
      if @funding_source.update(form_params)
        notify_user(:notice, "The funding program was successfully updated.")
        format.html { redirect_to funding_source_url(@funding_source) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @funding_source.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /funding_sources/1
  # DELETE /funding_sources/1.json
  def destroy
    @funding_source.destroy
    notify_user(:notice, "The funding program was successfully removed.")
    respond_to do |format|
      format.html { redirect_to funding_sources_url }
      format.json { head :no_content }
    end
  end

  def find_fiscal_year_range
    program_id = params[:program_id]
    program = FundingSource.find_by(id: program_id)

    result = program.find_all_valid_fiscal_years

    respond_to do |format|
      format.json { render json: result.to_json }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funding_source
      @funding_source = FundingSource.find_by_object_key(params[:id])
      if @funding_source.nil?
        redirect_to '/404'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:funding_source).permit(FundingSource.allowable_params)
    end

  def check_for_cancel
    unless params[:cancel].blank?
      # get the funding source, if one was being edited
      if params[:id]
        redirect_to(funding_source_url(@funding_source))
      else
        redirect_to(funding_sources_url)
      end
    end
  end

end

app/views/funding_sources/_chart_scripts.html.erb
<script type="text/javascript">

	google.load("visualization", "1", {
		'packages': ['corechart']
	});
	
	var div_id = 'chart_div';
	var chart_type = 'combo';
	var chart_options = {
      hAxis: {title: 'Fiscal Year'},
      vAxis: {title: '$'},
      fontSize: 10,
      isStacked: false,
	  seriesType: "bars",
	  series: {3: {type: "line"}}
    };
  

	google.setOnLoadCallback(draw_chart);

  	// Called when the Visualization API is loaded.
  	function draw_chart() {

		var chart_data = new google.visualization.DataTable();
		
	    chart_data.addColumn('string', 'Fiscal Year');
	    chart_data.addColumn('number', 'Allocated');
	    chart_data.addColumn('number', 'Spent');
	    chart_data.addColumn('number', 'Committed');
	    chart_data.addColumn('number', 'Balance');
		
		<% @funding_source.cash_flow(@org).each do |row| %>
			chart_data.addRow([
				<% row.each_with_index do |el, idx| %>
					<% if idx == 0 %>
						'<%= row[idx] %>' 
					<% else %>
						,{v: <%= row[idx].to_i %>, f: '<%= format_as_currency(row[idx]) %>'} 
					<% end %>
				<% end %>
			]);
		<% end %>
  
  		transam.draw_chart(div_id, chart_type, chart_options, chart_data);	
	};

	// Handle the resize event and make sure the chart is redrawn for the new size
	window.onresize = function() {
		draw_chart();
	};
  
  	$(document).ready(function() {
    	draw_chart();
  	});
  	
</script>

app/views/funding_sources/_comments.html.haml
.row
  .col-md-12{:style => 'height:200px;overflow-y:auto;'}
    - if @funding_source.comments.empty?
      %p There are no comments for this funding program.
    - else
      = render :partial => 'shared/comments', :locals => {:comments => @funding_source.comments}

- if can? :create, @funding_source.comments.build
  .row
    .col-md-12
      %fieldset
        %legend Add Comment
        = form_for [@funding_source, Comment.new], :html => {:multipart => true, :class => 'form-vertical comment_form' }, :url => funding_source_comments_path(@funding_source, Comment.new), :role => 'form' do |f|
          .form-group
            = f.text_area :comment, :class => 'form-control', :placeholder => 'Enter a new comment...', :required => true, :minlength => 10, :maxlength => 254
          = f.submit :class => 'btn btn-primary', :id => 'comment_submit'

:javascript

  // jquery validations
  $('.comment_form').validate({
    ignore: [], //validate hidden fields
    submitHandler: function(form) {
      form.submit();
    }
  });

app/views/funding_sources/_description.html.haml
= format_field("Program Eligibility", format_as_list(funding_source.organizations) )
.row
  .col-xs-12
    %fieldset
      %legend.panel-legend Description
      .desc-content
        = funding_source.description

%br
.row
  .col-xs-12
    %fieldset
      %legend.panel-legend Details
      .desc-content
        = funding_source.details
      %legend.panel-legend Type
      .desc-content
        = funding_source.formula_fund.present? ? "Formula" : (funding_source.discretionary_fund.present? ? "Discretionary" : "Unknown")
      %legend.panel-legend Source
      .desc-content
        = funding_source.funding_source_type
      %legend.panel-legend Life of $
      .desc-content
        = format_as_integer(funding_source.life_in_years)
      %legend.panel-legend Inflation Rate
      .desc-content
        = funding_source.inflation_rate
      %legend.panel-legend Pcnt Match
      .desc-content
        = format_as_percentage(funding_source.match_required, 3)
      %legend.panel-legend Start
      .desc-content
        = format_as_fiscal_year(funding_source.fy_start)
      %legend.panel-legend End
      .desc-content
        = format_as_fiscal_year(funding_source.fy_end)
      -# = format_as_text(funding_source.details)

app/views/funding_sources/_details.html.haml
%ul.nav.nav-tabs
  %li
    %a{:href => "#desc", :data =>{:toggle => 'tab'}}
      = "Details"

  = nav_tab_count_tag("#grant", "Grants", @funding_source.grants.count)
  = nav_tab_count_tag("#asst", "Assets", @funding_source.assets.count)

  = nav_tab_count_tag("#docs", "Documents", @funding_source.documents.count)
  = nav_tab_count_tag("#comments", "Comments", @funding_source.comments.count)

.tab-content{:style => 'max-height:400px;overflow-y: auto;'}
  .tab-pane.fade#desc
    .tab-content
      = render :partial => 'description', :locals => {:funding_source => @funding_source}

  .tab-pane.fade#grant
    .tab-content
      = render :partial => 'grants/index_table', :locals => {:grants => @funding_source.grants}

  .tab-pane.fade#asst
    .tab-content
      - if @funding_source.assets.empty?
        %p There are no assets associated with this program.
      - else
        = render :partial => 'assets/asset_compact_datatable', :locals => {:assets => @funding_source.assets.distinct}

  .tab-pane.fade#docs
    .tab-content
      = render 'documents'

  .tab-pane.fade#comments
    .tab-content
      = render 'comments'

app/views/funding_sources/_index_table.html.haml
:ruby
  table_dom_id = SecureRandom.hex
  show_actions ||= 0

#subheader-label
  %h2 Programs

- if show_actions == 1
  #programs_table_actions.btn-toolbar
    = render :partial => "funding_sources/index_actions"




= javascript_include_tag  "https://kit.fontawesome.com/#{ENV['FONT_AWESOME']}.js"
.library-table
  %table.elbat{:id => table_dom_id,
    :use => 'true',
    :data => {:use => 'true',
      :table_code => 'programs',
      :side => 'client',
      :current_page => '0',
      :current_page_size => '10',
      :page_sizes => "10,20,50,100",
      :search => 'client',
      :export => "['csv', 'txt']",
      :columns => '{"name":{"name":"Program Name","type":"drilldown-link","width":"25%"},
                    "full_name":{"name":"Full Name","width":"15%"},
                    "1":{"name":"Source","width":"12%"},
                    "2":{"name":"Program Type","width":"15%"},
                    "3":{"name":"Inflation Rate","width":"10%"},
                    "4":{"name":"Life of $ (yrs)","width":"10%"},
                    "5":{"name":"% Match","width":"10%"},
                    "6":{"name":"Valid From","width":"10%"},
                    "7":{"name":"Valid To","width":"10%"},
                    "8":{"name":"Description","width":"10%"},
                    "9":{"name":"Details","width":"8%"},
                    "10":{"name":"External ID","width":"10%"},
                    "11":{"name":"Object Key","width":"12%"},
                    "created_by":{"name":"Created By","width":"12%"},
                    "status":{"name":"Program Status", "width":"10%"},
                    "12":{"name":"Actions","type":"action-column","width":"15%"}}',
      :selected_columns => "name,full_name,1,2,3,4,5,6,7,created_by,status,12",
      :cookies => "true",
      :sort => 'client',
      :params => "{}",
      :filter => "[]",
      :data_source => 'client',
      :url => ''}}
  - funding_sources.each_with_index do |f, index|
    %div.actions{:id => index}
      %a.transam-popover{data: {placement: 'left', toggle: 'popover', html: 'true', content: "<b>Description:</b>#{f.description}<br><b>Details:</b>#{f.details}<br><b>Type:</b>#{f.formula_fund.present? ? "Formula" : (f.discretionary_fund.present? ? "Discretionary" : "Unknown")}<br><b>Source:</b>#{f.funding_source_type}<br><b>Life of $:</b>#{format_as_integer(f.life_in_years)}<br><b>% Match:</b>#{format_as_percentage(f.match_required, 3)}<br><b>Start:</b>#{format_as_fiscal_year(f.fy_start)}<br><b>End:</b>#{format_as_fiscal_year(f.fy_end)}"}, title: "#{f.name}", tabindex: '0'}
        %i.fa.fa-info-circle
      - if can? :update, f
        = link_to edit_funding_source_path(f, :format => :js), :id => "#{f.object_key}", :class => "button btn-xs edit_flyout", :title => "Edit program", :remote => true do
          %i.fa.fa-edit.fa-1-5x.text-success
        - if (can? :destroy, f) && f.deleteable?
          = link_to funding_source_path(f), :method => :delete, :data => {:confirm => "Are you sure? The action cannot be undone."}  do
            %i.fa.fa-trash-o.fa-fw.text-danger
    
    
    :javascript
      add_row('#{table_dom_id}',
      {                  
        "name": '#{h link_to f.name, funding_source_path(f) }',
        "1": '#{h f.funding_source_type }',
        "full_name": '#{h f.full_name }',
        "2": '#{h f.formula_fund.present? ? "Formula" : (f.discretionary_fund.present? ? "Discretionary" : "Unknown") }',
        "3": '#{h f.inflation_rate.present? ? format_as_percentage(f.inflation_rate, 3) : "" }',
        "4": '#{h format_as_integer(f.life_in_years) }',
        "5": '#{h format_as_percentage(f.match_required, 3) }',
        "6": '#{h format_as_fiscal_year(f.fy_start) }',
        "7": '#{h format_as_fiscal_year(f.fy_end) }',
        "8": '#{h f.description }',
        "9": '#{h f.details }',
        "10": '#{h f.external_id }',
        "11": '#{h f.object_key }',
        "status":'#{h f.active ? "Active" : "Inactive" }',
        "created_by":'#{h current_user.organization.short_name }',
      }, #{index});
      // TEMP UNTIL WE DO THIS FOR REAL
      // TODO: PLEASE DON'T LET THIS GO TO PRODUCTION
      // HACKY HACK IS HACKY
      add_aux_queue('#{table_dom_id}',()=>{
        $("##{table_dom_id} ~ .actions##{index}").detach().appendTo($("##{table_dom_id} .action-column").eq(#{index}).find(".cell-text"));
      });
      //add_aux_queue('#{table_dom_id}',()=>$(".actions").eq(#{index}).detach().appendTo($("##{table_dom_id} .action-column").eq(#{index}).find(".cell-text")));

  -# :javascript
  -#   $(".button.flyout").on("click", (e)=>{
  -#     //console.log($(e.target).closest(".flyout").find(".flyout_wrapper"));
  -#     // e.stopImmediatePropagation();
  -#     if(!$(e.target).attr("flyout")) {
  -#       add_flyout(e.target, "Edit Program", '#{raw escape_javascript(render :template => "funding_sources/edit", :locals => {:obj => @funding_source})}', "flyout-right");
  -#       $(e.target).attr("flyout", true);
  -#       //$(e.target).closest(".flyout").find(".flyout_wrapper").toggleClass("close");
  -#     }
  -#   });





-# .table-responsive
-#   %table.table.table-hover{:id => table_dom_id, :data => {:toggle => 'table',
-#     :pagination => 'true',
-#     :show_pagination_switch => 'false',
-#     :page_list => "5, 10, 20, 50, 100, 200, 10000]",
-#     :page_size => current_user.num_table_rows,
-#     :search => 'false',
-#     :toolbar => "#programs_table_actions",
-#     :export_types => "['csv', 'txt', 'excel']",
-#     :show_export => 'true',
-#     :show_columns => 'true',
-#     :cookie => 'true',
-#     :cookie_id_table => "funding_sources_id",
-#     :cookie_expire => "1y"}}

-#     %thead
-#       %tr
-#         %th.center{:data => {:visible => 'false'}} Object Key
-#         %th.center{:data => {:visible => 'false', :sortable => 'true'}} External ID
-#         %th.center{:data => {:sortable => 'true'}} Name
-#         %th.center{:data => {:sortable => 'true'}} Source

-#         %th.center{:data => {:sortable => 'true'}} Type
-#         %th.center{:data => {:sortable => 'true', :formatter => 'percentage_formatter'}} Inflation Rate

-#         %th.center{:data => {:sortable => 'true'}} Life of $ (yrs)
-#         %th.center{:data => {:sortable => 'true', :formatter => 'percentage_formatter'}} Pcnt Match

-#         %th.center{:data => {:sortable => 'true'}} Valid From
-#         %th.center{:data => {:sortable => "content":


-#         %th

-#     %tbody
-#       - funding_sources.each do |f|
-#         %tr{:id => f.object_key, :class => 'action-path'}
-#           %td.left= f.object_key
-#           %td.left= f.external_id
-#           =# add whitespace so always read as text and not number. JS plugin trims later
-#           %td.left{data: {tableexport: {msonumberformat: "\\@", value: "#{f.name}   "}}}
-#             = f.name
-#           %td.left= f.funding_source_type

-#           %td.center= f.formula_fund.present? ? 'Formula' : (f.discretionary_fund.present? ? 'Discretionary' : 'Unknown')
-#           %td.right= f.inflation_rate.present? ? f.inflation_rate : ''

-#           %td.center= format_as_integer(f.life_in_years)
-#           %td.right= f.match_required

-#           %td.center= format_as_fiscal_year(f.fy_start)
-#           %td.center= format_as_fiscal_year(f.fy_end)

-#           %td.center.nowrap{:data => {:field => 'action-cell'}}
-#             %a.transam-popover{data: {placement: 'left', toggle: 'popover', html: 'true', content: "#{f.description}<br>#{f.details}"}, title: 'Details', tabindex: '0'}
-#               %i.fa.fa-info-circle
-#             - if can? :update, f
-#               = link_to edit_funding_source_path(f), :class => "button btn-xs", :title => "Edit program" do
-#                 %i.fa.fa-edit.fa-1-5x.text-success
-#               - if (can? :destroy, f) && f.deleteable?
-#                 = link_to funding_source_path(f), :method => :delete, :data => {:confirm => "Are you sure? The action cannot be undone."}  do
-#                   %i.fa.fa-trash-o.fa-fw.text-danger

= render 'shared/table_formatters'

:javascript

  $('#' + '#{table_dom_id}').on('post-body.bs.table', function () {
    $('.transam-popover').popover({
      trigger: 'hover'
    });

    $('.transam-tooltip').tooltip();
  });

  //$('#' + '#{table_dom_id}').on('click', 'td', function () {
  //  var path = "#{funding_source_path('xxx')}";
  //  var row = $(this).parent('tr').attr('id');
  //
  //  if ($(this).attr('data-field') != 'action-cell') {
  //    var url = path.replace("xxx", row);
  //    document.location.href = url;
  //  }
  //});

app/views/funding_sources/_scripts.html.haml
:javascript

  $(document).ready(function() {
    transam.make_same_height('.header-part');

    // Manage the tabs
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e) {
      // save the latest tab
      var this_tab = $(this).attr('href');
      //alert(this_tab);
      transam.set_ui_key_value('fs_tab', this_tab);
      if (this_tab == '#chrt') {
        draw_chart();
      }
    });
  });
  $(function() {
    var last_tab = transam.get_ui_key_value('fs_tab');
    if (last_tab) {
      $('a[href="'+last_tab+'"]').tab('show');
    } else {
      // Default to the first tab if no tab is stored
      $('a[data-toggle="tab"]:first').tab('show');
    }
  });

app/views/funding_sources/details.js.erb
$('#federal_fund_details').html("<%= escape_javascript(render 'fund_details') %>");