config/routes.rb
Rails.application.routes.draw do

  resources :general_ledger_mappings
  resources :funding_sources, :path => :funding_programs do
    collection do
      get 'details'
      get 'find_fiscal_year_range'
    end
    resources :comments
    resources :documents
  end

  resources :grants do
    resources :grant_apportionments
    resources :grant_amendments

    member do
      get 'summary_info'
      get 'fire_workflow_event'
    end
  end



  resources :general_ledger_accounts do
    collection do
      get 'get_accounts'
      get 'check_grant_budget'
      get 'toggle_archive'
    end
  end

  resources :inventory, :only => [], :controller => 'assets' do
    collection do
      get 'get_general_ledger_account'
    end

    member do
      get 'get_book_value_on_date'
      get 'get_depreciation_months_left'
      get 'edit_depreciation'
      post 'update_depreciation'
    end

    resources :expenditures
  end

  resources :expenditures, :only => [] do
    resources :comments
    resources :documents
  end
end

app/views/searches/_general_ledger_account_search_form.html.haml
= render :layout => "search_panel" do |f|
  .panel-group#search-fields

    .panel.panel-info
      .panel-heading
        = link_to 'General Ledger Account', '#gla', :role => 'button', :data => {:toggle => 'collapse'}, :aria => {:expanded => true}

      .panel-body#gla.collapse
        .row
          .col-md-3
            = f.input :mapping, collection: [['Asset Accounts', 'asset_account'], ['Accumulated Depreciation Accounts', 'accumulated_depr_account'], ['Depreciation Expense Accounts', 'depr_expense_account'], ['Gain/Loss Accounts', 'gain_loss_account']], label: 'GL Mappings', input_html: { multiple: true }
          .col-md-3
            = f.input :account_number
          .col-md-3
            = f.input :name, :label => 'Account Name'

    .panel.panel-info
      .panel-heading
        = link_to 'General Ledger Entries', '#gla-entries', :role => 'button', :data => {:toggle => 'collapse'}, :aria => {:expanded => true}
      .panel-body#gla-entries.collapse
        .row
          .col-md-3
            = f.input :event_date, :wrapper => :vertical_prepend, :label => "Entry Date" do
              .input-group-btn
                %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
                %ul.dropdown-menu{:role => "menu"}
                  %li
                    %a{:data => {:compare => "-1"}} Before
                  %li
                    %a{:data => {:compare => "0"}} On
                  %li
                    %a{:data => {:compare => "1"}} After
                = f.input_field :event_date_comparator, :as => :hidden, :value => '0'
              = f.date_field :event_date, :class => "form-control"
          .col-md-3
            = f.input :description, :label => 'Entry Description'


    .panel.panel-info
      .panel-heading
        = link_to 'Assets', '#asset', :role => 'button', :data => {:toggle => 'collapse'}, :aria => {:expanded => true}

      .panel-body#asset.collapse
        #types
          .row
            .col-md-3
              = f.input :asset_type_id, :collection => AssetType.active.map { |type| [type.name, type.id, :class => type.class_name] },  input_html: { multiple: true }, :label => "Type"
            .col-md-3
              = f.input :asset_subtype_id, collection: AssetType.active, as: :grouped_select, group_method: :asset_subtypes, input_html: { multiple: true }, :label => "Asset Subtype"
            .col-md-3
              = f.input :asset_tag

app/views/searches/_general_ledger_account_search_form_actions.html.haml
.btn-group.pull-right.panel-action{:style => "padding-right: 5px;"}
  %button.btn.btn-primary.btn-sm.dropdown-toggle{:data => {:toggle => 'dropdown'}}
    %i.fa.fa-cog
    = " Actions"
    %span.caret
  %ul.dropdown-menu{:role => 'menu'}
    %li
      = link_to new_saved_search_path(search_type_id: @search_type.id), :remote => true, :title => 'Save query' do
        %i.fa.fa-floppy-o.fa-fw
        = " Save query parameters"

app/views/searches/_general_ledger_account_search_form_scripts.html.erb
<script type="text/javascript">

  transam.make_fiscal_year('input.fiscal_year');

  $(document).ready(function() {

    transam.enable_date_pickers();
    transam.make_same_height('.form_part');

    // Search Form AJAX event handling // See https://github.com/rails/jquery-ujs/wiki/ajax
    $("form").on("ajax:send", function(xhr) {
      $('#results_table').hide();
      $('#spinner').show();
    })
    .on("ajax:success", function(xhr) {
      $(".search-panel").collapse('hide');
      $("#search-panel-controller").fadeIn();
    })
    .on("ajax:complete", function(xhr, status) {
      $('#spinner').hide();
    });


    //Allows disabled form fields to submit as blank values, which is necessary to prevent the asset searcher from interpreting them as nil.
    $("form").submit(function(){
      $("input:disabled").removeAttr("disabled").prop('selected', false).val('');
    });

    // Type Selector Handler, Populates the Asset Search form and disables fields depending on what the user clicks chooses.

    $('#searcher_asset_type_id').on('click', function(event) {
      var selectedOptions = $('#searcher_asset_type_id option:selected')
      typeNames = $.map(selectedOptions, function(option){
        return $(option).text();
      });

      $('#searcher_asset_subtype_id').find('optgroup').each(function(index, group){
          var label = $(group).attr('label')
          if ($.inArray(label, typeNames) === -1){
              $(group).children('option').prop('selected', false);
              $(group).hide();
              $(group).attr("disabled", "disabled")
          } else {
              $(group).fadeIn();
              $(group).removeAttr("disabled")
          }
      });

    }); // end of type selector scripts

    // Set btn-dropdown text from set values in the hidden fields
    var hidden_fields = $(".input-group-btn input[type='hidden']");
    hidden_fields.each(function(selector) {
      var selected_link = $(this).prev("ul").find("a[data-compare=" + ($(this).val() ? $(this).val() : 0)+ "]");
      var text = selected_link.html() + " ";
      var btn = $(this).prevAll("button");
      btn.html(text).append("<span class='caret'></span>");
    });

    // When selecting from the button-dropdowns, set a hidden field appropriately
    $(".input-group-btn a").on("click", function() {
      // Handle btn-dropdown by setting relevant variable in hidden field
      $(this).parents("ul").siblings("input:hidden").val($(this).attr("data-compare"));
      $(this).parents("ul").prev("button").text($(this).text() + " ");
      $(this).parents("ul").prev("button").append("<span class='caret'></span>");
    });


  }); // end of document ready scripts

</script>

app/views/searches/_general_ledger_account_search_results_table.html.haml
.table-responsive
  %table.table.table-condensed.table-hover{:id => 'search_gla_table',
    :data => {:toggle => 'table',
    :url => new_search_path(:format => :json, :search_type => @search_type.id),
    :card_view => "false",
    :pagination => 'true',
    :sort_order => 'asc',
    :sortable => 'true',
    :side_pagination => 'server',
    :show_pagination_switch => 'false',
    :page_number => '1',
    :page_list => "5, 10, 20, 50, 100, 200, 10000]",
    :page_size => current_user.num_table_rows,
    :search => 'false',
    :show_columns => 'true',
    :show_export => 'true',
    :row_style => 'row_style',
    :click_to_select => 'true',
    :show_export => 'true',
    :id_field => 'object_key',
    :export_types => "['csv', 'txt', 'excel']",
    :cookie => 'true',
    :cookie_id_table => "asset_search_id",
    :cookie_expire => "1y",
    :maintain_selected => 'true',
    :single_select => 'false'}}
    %thead
      %tr

        %th.center.nowrap{:data => {:field => "general_ledger_account_object_key", :align => 'left', :visible => 'false'}} Object Key

        - if @organization_list.count > 1
          %th.center.nowrap{:data => {:field => "asset_organization", :sortable => 'true'}} Agency
        - else
          %th.center.nowrap{:data => {:field => "asset_organization", :sortable => 'true', :visible => 'false'}} Agency

        %th.center.nomrap{:data => {:field => "event_date", :align => 'left', :sortable => 'true', :formatter => 'date_formatter'}} Entry Date
        %th.center.nomrap{:data => {:field => "general_ledger_account_account_number", :align => 'left', :sortable => 'true'}} Account
        %th.center.nowrap{:data => {:field => "asset", :align => 'left', :sortable => 'true'}} Asset
        %th.center{:data => {:field => "description", :align => 'left', :sortable => 'true'}} Description
        %th.center.nowrap{:data => {:field => "amount", :align => 'right', :sortable => 'true', :formatter => 'currency_formatter'}} Amount

= render 'shared/table_formatters'

:javascript

  var path = '#{general_ledger_account_path("x")}';

  function row_style(row, index) {
    return 'action-path';
  };

  $('#search_gla_table').on('click-row.bs.table', function (e, row, $element) {
    var url = path.replace("x", row['general_ledger_account_object_key']);
    document.location.href = url;
  }).on('sort.bs.table', function(e, name, order) {
    $('#search_gla_table').bootstrapTable('selectPage', 1);
  }).on('post-body.bs.table', function() {
    $('.fixed-table-container').css('min-height', '300px');
    $('#search_gla_table > tbody > tr').addClass('action-path');
  });

  $(window).resize(function() {
    $('#search_gla_table').bootstrapTable('resetView');
  });

app/views/searches/_general_ledger_account_searcher_button.html.haml
- if ChartOfAccount.count > 0
  .btn-group{:role => 'group'}
    = link_to reset_searches_path(search_type: search_type.id ), :role => 'button', :class => 'btn btn-default' do
      = "New #{search_type} Query"